web:
  upload-path: E:\flower\user\

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hua?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: yumaoying
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/resources/,classpath:/static/,file:${web.upload-path}
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
    timeout: 0
  mail:
    port: 597
    host: smtp.qq.com
    username: 1101271954@qq.com
    password: hkvzvkqwvdcwbaac
    default-encoding: utf-8
    properties:
            mail:
              smtp:
                auth: true
                starttls:
                  enable: true
                  required: true
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: true
      port: 35730


server:
  port: 34002
  context-path: /chunzhiyu




